# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Siddharth Majhi
title: Student
email: majhysiddharth17121996@gamil.com
website: www.github.com/yoshimitsu117

# Social links
twitter_username: SiddharthMajhi2
github_username:  yoshimitsu117
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: yoshimitsu_
linkedin_username: siddharth-majhi-5b8698129
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  My name is Siddharth Majhi and I am currently a 4th year student pursuing Bachelor of Technology in Information Technology from National Institute Of Science And Technology,Berhampur.A competitive programmer who loves solving problems,reading machine learning blogs,sketching and travelling .Apart from all these,another thing that interests me is Web developement.
  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in things mentioned above:
   - Dancing
   - Gaming
   - Singing
   - Spreading the knowledge 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
